
      <!DOCTYPE HTML>
      <html lang=en>
        <meta charset=utf-8>
        <title>manakai</title>
        <link rel=stylesheet href="https://manakai.github.io/css/pod.css">
        <meta name=viewport content="width=device-width">

        <h1><a href="../" rel=top>manakai</a></h1>

        





<hgroup><h1><code>Error</code></h1><h2>Error/exception handling in an OO-ish way</h2></hgroup><section id="WARNING"><h1>WARNING</h1>

<p>Using the "Error" module is <b>no longer recommended</b> due to the black-magical nature of its syntactic sugar,
which often tends to break.
Its maintainers have stopped actively writing code that uses it,
and discourage people from doing so.
See the "SEE ALSO" section below for better recommendations.</p>

</section><section id="SYNOPSIS"><h1>SYNOPSIS</h1>

<pre><code>    use Error qw(:try);

    throw Error::Simple( "A simple error");

    sub xyz {
        ...
        record Error::Simple("A simple error")
            and return;
    }
 
    unlink($file) or throw Error::Simple("$file: $!",$!);

    try {
        do_some_stuff();
        die "error!" if $condition;
        throw Error::Simple "Oops!" if $other_condition;
    }
    catch Error::IO with {
        my $E = shift;
        print STDERR "File ", $E-&gt;{'-file'}, " had a problem\n";
    }
    except {
        my $E = shift;
        my $general_handler=sub {send_message $E-&gt;{-description}};
        return {
            UserException1 =&gt; $general_handler,
            UserException2 =&gt; $general_handler
        };
    }
    otherwise {
        print STDERR "Well I don't know what to say\n";
    }
    finally {
        close_the_garage_door_already(); # Should be reliable
    }; # Don't forget the trailing ; or you might be surprised</code></pre>

</section><section id="DESCRIPTION"><h1>DESCRIPTION</h1>

<p>The <code>Error</code> package provides two interfaces. Firstly <code>Error</code> provides a procedural interface to exception handling. Secondly <code>Error</code> is a base class for errors/exceptions that can either be thrown, for subsequent catch, or can simply be recorded.</p>

<p>Errors in the class <code>Error</code> should not be thrown directly, but the user should throw errors from a sub-class of <code>Error</code>.</p>

</section><section id="PROCEDURAL_INTERFACE"><h1>PROCEDURAL INTERFACE</h1>

<p><code>Error</code> exports subroutines to perform exception handling. These will be exported if the <code>:try</code> tag is used in the <code>use</code> line.</p>

<dl>
<dt id="try_BLOCK_CLAUSES">try BLOCK CLAUSES</dt>

<dd>
<p><code>try</code> is the main subroutine called by the user. All other subroutines exported are clauses to the try subroutine.</p>

<p>The BLOCK will be evaluated and, if no error is throw, try will return the result of the block.</p>

<p><code>CLAUSES</code> are the subroutines below, which describe what to do in the event of an error being thrown within BLOCK.</p>

</dd><dt id="catch_CLASS_with_BLOCK">catch CLASS with BLOCK</dt>

<dd>
<p>This clauses will cause all errors that satisfy <code>$err-&gt;isa(CLASS)</code> to be caught and handled by evaluating <code>BLOCK</code>.</p>

<p><code>BLOCK</code> will be passed two arguments. The first will be the error being thrown. The second is a reference to a scalar variable. If this variable is set by the catch block then, on return from the catch block, try will continue processing as if the catch block was never found. The error will also be available in <code>$@</code>.</p>

<p>To propagate the error the catch block may call <code>$err-&gt;throw</code></p>

<p>If the scalar reference by the second argument is not set, and the error is not thrown. Then the current try block will return with the result from the catch block.</p>

</dd><dt id="except_BLOCK">except BLOCK</dt>

<dd>
<p>When <code>try</code> is looking for a handler, if an except clause is found <code>BLOCK</code> is evaluated. The return value from this block should be a HASHREF or a list of key-value pairs, where the keys are class names and the values are CODE references for the handler of errors of that type.</p>

</dd><dt id="otherwise_BLOCK">otherwise BLOCK</dt>

<dd>
<p>Catch any error by executing the code in <code>BLOCK</code></p>

<p>When evaluated <code>BLOCK</code> will be passed one argument, which will be the error being processed. The error will also be available in <code>$@</code>.</p>

<p>Only one otherwise block may be specified per try block</p>

</dd><dt id="finally_BLOCK">finally BLOCK</dt>

<dd>
<p>Execute the code in <code>BLOCK</code> either after the code in the try block has successfully completed, or if the try block throws an error then <code>BLOCK</code> will be executed after the handler has completed.</p>

<p>If the handler throws an error then the error will be caught, the finally block will be executed and the error will be re-thrown.</p>

<p>Only one finally block may be specified per try block</p>
</dd>
</dl>

</section><section id="COMPATIBILITY"><h1>COMPATIBILITY</h1>

<p><a href="../Moose" class="podlinkpod">Moose</a> exports a keyword called <code>with</code> which clashes with Error's. This example returns a prototype mismatch error:</p>

<pre><code>    package MyTest;

    use warnings;
    use Moose;
    use Error qw(:try);</code></pre>

<p>(Thanks to <code>maik.hentsche@amd.com</code> for the report.).</p>

</section><section id="CLASS_INTERFACE"><h1>CLASS INTERFACE</h1>

<section id="CONSTRUCTORS"><h1>CONSTRUCTORS</h1>

<p>The <code>Error</code> object is implemented as a HASH. This HASH is initialized with the arguments that are passed to it's constructor. The elements that are used by, or are retrievable by the <code>Error</code> class are listed below, other classes may add to these.</p>

<pre><code>        -file
        -line
        -text
        -value
        -object</code></pre>

<p>If <code>-file</code> or <code>-line</code> are not specified in the constructor arguments then these will be initialized with the file name and line number where the constructor was called from.</p>

<p>If the error is associated with an object then the object should be passed as the <code>-object</code> argument. This will allow the <code>Error</code> package to associate the error with the object.</p>

<p>The <code>Error</code> package remembers the last error created, and also the last error associated with a package. This could either be the last error created by a sub in that package, or the last error which passed an object blessed into that package as the <code>-object</code> argument.</p>

<dl>
<dt id="Error->new()"><code>Error-&gt;<strong id="member-new()">new()</strong></code></dt>

<dd>
<p>See the Error::Simple documentation.</p>

</dd><dt id="throw_(_[_ARGS_]_)">throw ( [ ARGS ] )</dt>

<dd>
<p>Create a new <code>Error</code> object and throw an error, which will be caught by a surrounding <code>try</code> block, if there is one. Otherwise it will cause the program to exit.</p>

<p><code>throw</code> may also be called on an existing error to re-throw it.</p>

</dd><dt id="with_(_[_ARGS_]_)">with ( [ ARGS ] )</dt>

<dd>
<p>Create a new <code>Error</code> object and returns it. This is defined for syntactic sugar, eg</p>

<pre><code>    die with Some::Error ( ... );</code></pre>

</dd><dt id="record_(_[_ARGS_]_)">record ( [ ARGS ] )</dt>

<dd>
<p>Create a new <code>Error</code> object and returns it. This is defined for syntactic sugar, eg</p>

<pre><code>    record Some::Error ( ... )
        and return;</code></pre>
</dd>
</dl>

</section><section id="STATIC_METHODS"><h1>STATIC METHODS</h1>

<dl>
<dt id="prior_(_[_PACKAGE_]_)">prior ( [ PACKAGE ] )</dt>

<dd>
<p>Return the last error created, or the last error associated with <code>PACKAGE</code></p>

</dd><dt id="flush_(_[_PACKAGE_]_)">flush ( [ PACKAGE ] )</dt>

<dd>
<p>Flush the last error created, or the last error associated with <code>PACKAGE</code>.It is necessary to clear the error stack before exiting the package or uncaught errors generated using <code>record</code> will be reported.</p>

<pre><code>     $Error-&gt;flush;</code></pre>
</dd>
</dl>

</section><section id="OBJECT_METHODS"><h1>OBJECT METHODS</h1>

<dl>
<dt id="stacktrace">stacktrace</dt>

<dd>
<p>If the variable <code>$Error::Debug</code> was non-zero when the error was created, then <code>stacktrace</code> returns a string created by calling <code>Carp::longmess</code>. If the variable was zero the <code>stacktrace</code> returns the text of the error appended with the filename and line number of where the error was created, providing the text does not end with a newline.</p>

</dd><dt id="object">object</dt>

<dd>
<p>The object this error was associated with</p>

</dd><dt id="file">file</dt>

<dd>
<p>The file where the constructor of this error was called from</p>

</dd><dt id="line">line</dt>

<dd>
<p>The line where the constructor of this error was called from</p>

</dd><dt id="text">text</dt>

<dd>
<p>The text of the error</p>

</dd><dt id="$err->associate($obj)"><code>$err-&gt;<strong id="member-associate($obj)">associate($obj)</strong></code></dt>

<dd>
<p>Associates an error with an object to allow error propagation. I.e:</p>

<pre><code>    $ber-&gt;encode(...) or
        return Error-&gt;prior($ber)-&gt;associate($ldap);</code></pre>
</dd>
</dl>

</section><section id="OVERLOAD_METHODS"><h1>OVERLOAD METHODS</h1>

<dl>
<dt id="stringify">stringify</dt>

<dd>
<p>A method that converts the object into a string. This method may simply return the same as the <code>text</code> method, or it may append more information. For example the file name and line number.</p>

<p>By default this method returns the <code>-text</code> argument that was passed to the constructor, or the string <code>"Died"</code> if none was given.</p>

</dd><dt id="value">value</dt>

<dd>
<p>A method that will return a value that can be associated with the error. For example if an error was created due to the failure of a system call, then this may return the numeric value of <code>$!</code> at the time.</p>

<p>By default this method returns the <code>-value</code> argument that was passed to the constructor.</p>
</dd>
</dl>

</section></section><section id="PRE-DEFINED_ERROR_CLASSES"><h1>PRE-DEFINED ERROR CLASSES</h1>

<section id="Error::Simple"><h1>Error::Simple</h1>

<p>This class can be used to hold simple error strings and values. It's constructor takes two arguments. The first is a text value, the second is a numeric value. These values are what will be returned by the overload methods.</p>

<p>If the text value ends with <code>at file line 1</code> as $@ strings do, then this infomation will be used to set the <code>-file</code> and <code>-line</code> arguments of the error object.</p>

<p>This class is used internally if an eval'd block die's with an error that is a plain string. (Unless <code>$Error::ObjectifyCallback</code> is modified)</p>

</section></section><section id="$Error::ObjectifyCallback"><h1>$Error::ObjectifyCallback</h1>

<p>This variable holds a reference to a subroutine that converts errors that are plain strings to objects. It is used by Error.pm to convert textual errors to objects, and can be overrided by the user.</p>

<p>It accepts a single argument which is a hash reference to named parameters. Currently the only named parameter passed is <code>'text'</code> which is the text of the error, but others may be available in the future.</p>

<p>For example the following code will cause Error.pm to throw objects of the class MyError::Bar by default:</p>

<pre><code>    sub throw_MyError_Bar
    {
        my $args = shift;
        my $err = MyError::Bar-&gt;new();
        $err-&gt;{'MyBarText'} = $args-&gt;{'text'};
        return $err;
    }

    {
        local $Error::ObjectifyCallback = \&amp;throw_MyError_Bar;

        # Error handling here.
    }</code></pre>

</section><section id="MESSAGE_HANDLERS"><h1>MESSAGE HANDLERS</h1>

<p><code>Error</code> also provides handlers to extend the output of the <code>warn()</code> perl function, and to handle the printing of a thrown <code>Error</code> that is not caught or otherwise handled. These are not installed by default, but are requested using the <code>:warndie</code> tag in the <code>use</code> line.</p>

<pre><code> use Error qw( :warndie );</code></pre>

<p>These new error handlers are installed in <code>$SIG{__WARN__}</code> and <code>$SIG{__DIE__}</code>. If these handlers are already defined when the tag is imported, the old values are stored, and used during the new code. Thus, to arrange for custom handling of warnings and errors, you will need to perform something like the following:</p>

<pre><code> BEGIN {
   $SIG{__WARN__} = sub {
     print STDERR "My special warning handler: $_[0]"
   };
 }

 use Error qw( :warndie );</code></pre>

<p>Note that setting <code>$SIG{__WARN__}</code> after the <code>:warndie</code> tag has been imported will overwrite the handler that <code>Error</code> provides. If this cannot be avoided, then the tag can be explicitly <code>import</code>ed later</p>

<pre><code> use Error;

 $SIG{__WARN__} = ...;

 import Error qw( :warndie );</code></pre>

<section id="EXAMPLE"><h1>EXAMPLE</h1>

<p>The <code>__DIE__</code> handler turns messages such as</p>

<pre><code> Can't call method "foo" on an undefined value at examples/warndie.pl line 16.</code></pre>

<p>into</p>

<pre><code> Unhandled perl error caught at toplevel:

   Can't call method "foo" on an undefined value

 Thrown from: examples/warndie.pl:16

 Full stack trace:

         main::inner('undef') called at examples/warndie.pl line 20
         main::outer('undef') called at examples/warndie.pl line 23</code></pre>

</section></section><section id="SEE_ALSO"><h1>SEE ALSO</h1>

<p>See <a href="../Exception/Class" class="podlinkpod">Exception::Class</a> for a different module providing Object-Oriented exception handling, along with a convenient syntax for declaring hierarchies for them. It doesn't provide Error's syntactic sugar of <code>try { ... }</code>, <code>catch { ... }</code>, etc. which may be a good thing or a bad thing based on what you want. (Because Error's syntactic sugar tends to break.)</p>

<p><a href="../Error/Exception" class="podlinkpod">Error::Exception</a> aims to combine <a href="../Error" class="podlinkpod">Error</a> and <a href="../Exception/Class" class="podlinkpod">Exception::Class</a> "with correct stringification".</p>

<p><a href="../TryCatch" class="podlinkpod">TryCatch</a> and <a href="../Try/Tiny" class="podlinkpod">Try::Tiny</a> are similar in concept to Error.pm only providing a syntax that hopefully breaks less.</p>

</section><section id="KNOWN_BUGS"><h1>KNOWN BUGS</h1>

<p>None, but that does not mean there are not any.</p>

</section><section id="AUTHORS"><h1>AUTHORS</h1>

<p>Graham Barr &lt;gbarr@pobox.com&gt;</p>

<p>The code that inspired me to write this was originally written by Peter Seibel &lt;peter@weblogic.com&gt; and adapted by Jesse Glick &lt;jglick@sig.bsh.com&gt;.</p>

<p><code>:warndie</code> handlers added by Paul Evans &lt;leonerd@leonerd.org.uk&gt;</p>

</section><section id="MAINTAINER"><h1>MAINTAINER</h1>

<p>Shlomi Fish &lt;shlomif@iglu.org.il&gt;</p>

</section><section id="PAST_MAINTAINERS"><h1>PAST MAINTAINERS</h1>

<p>Arun Kumar U &lt;u_arunkumar@yahoo.com&gt;</p>

</section><section id="COPYRIGHT"><h1>COPYRIGHT</h1>

<p>Copyright (c) 1997-8 Graham Barr. All rights reserved. This program is free software; you can redistribute it and/or modify it under the same terms as Perl itself.</p>




</section>

        <sw-ads normal></sw-ads>
        <script src="https://manakai.github.io/js/global.js" async></script>

        <footer>
          <ul>
          <li><a href="../" rel=top>Top</a>
          </ul>
        </footer>
        <sw-ads-notes></sw-ads-notes>
    